<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Media\Icons\AreaAverage.png" />
    <None Remove="Media\Icons\FitImage.png" />
    <None Remove="Media\Icons\Info.png" />
    <None Remove="Media\Icons\MultipointSelection.png" />
    <None Remove="Media\Icons\PanHand.png" />
    <None Remove="Media\Icons\RectangleSelection.png" />
    <None Remove="Media\Icons\SelectAll.png" />
    <None Remove="Media\Icons\TrashCan.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ScottPlot.WPF" Version="5.1.59" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Media\Icons\AreaAverage.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Media\Icons\FitImage.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Media\Icons\Info.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Media\Icons\MultipointSelection.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Media\Icons\PanHand.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Media\Icons\RectangleSelection.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Media\Icons\SelectAll.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Media\Icons\TrashCan.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

	<ItemGroup>
		<None Update="PythonBridge\predict.py">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
